customers/urls.py
from django.urls import path

from .views import (
    customer_list_view,
    customer_create_view,
    customer_detail_view,
    customer_update_view,
    customer_detail_hx_view,
    customer_contact_update_hx_view,
    autosuggest,
)

app_name='customers'
urlpatterns = [
    path("", customer_list_view, name='list'),
    path("create/", customer_create_view, name='create'),
    path("name-autosuggest/", autosuggest, name='name-autosuggest'),
    path("hx/<int:parent_id>/contacts/<int:id>/", customer_contact_update_hx_view, name='hx-contact-detail'),
    path("hx/<int:parent_id>/contacts/", customer_contact_update_hx_view, name='hx-contact-create'),
    path("hx/<int:id>/", customer_detail_hx_view, name='hx-detail'),
    path("<int:id>/edit", customer_update_view, name='update'),
    path("<int:id>/", customer_detail_view, name='detail'),
]

studio_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import home_view

urlpatterns = [
    path('', home_view, name='home'),
    path('admin/', admin.site.urls),
    #path('', include('userprofile.urls')),
    path('userprofile/', include('django.contrib.auth.urls')),
    path('userprofile/', include('userprofile.urls')),
    path('customers/', include('customers.urls')),
    path('inventory/', include('inventory.urls')),
    path('purchase_orders/', include('purchase_orders.urls')),
    path('vendors/', include('vendors.urls')),
    path('workorders/', include('workorders.urls')),
    #path('scratch/', include('scratch.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vendors/urls.py
from django.urls import path

from .views import (
    vendor_list_view,
    vendor_create_view,
    vendor_detail_view,
    vendor_update_view,
    vendor_detail_hx_view,
    vendor_contact_update_hx_view,
)

app_name='vendors'
urlpatterns = [
    path("", vendor_list_view, name='list'),
    path("create/", vendor_create_view, name='create'),
    path("hx/<int:parent_id>/contacts/<int:id>/", vendor_contact_update_hx_view, name='hx-contact-detail'),
    path("hx/<int:parent_id>/contacts/", vendor_contact_update_hx_view, name='hx-contact-create'),
    path("hx/<int:id>/", vendor_detail_hx_view, name='hx-detail'),
    path("<int:id>/edit", vendor_update_view, name='update'),
    path("<int:id>/", vendor_detail_view, name='detail')
]

workorders/urls.py
from django.urls import path

from .views import (
    workorder_list_view,
    #workorder_create_view,
    workorder_detail_view,
    workorder_delete_view,
    workorder_detail_hx_view,
    workorder_update_view,
    workorder_inventory_update_hx_view,
    workorder_noninventory_update_hx_view,
    workorder_service_update_hx_view,
    workorder_invoice_update_hx_view,
    create_base,
    contacts,
    update_contact,
    #custom_workorder_create,
    service_detail,
    inventory_detail,
    workorder_service_detail,
    workorder_inventory_detail,
    
)

app_name='workorders'
urlpatterns = [
    path("", workorder_list_view, name='list'), #List All workorders
    path("createbase/", create_base, name='createbase'), #Create base details of new workorder
    path('contacts/', contacts, name='contacts'), #Fills the contact dropdown on createbase/
    path('updatecontact/', update_contact, name='update-contact'), ####
    path('servicedetail/', service_detail, name='service-detail'),
    path('inventorydetail/', inventory_detail, name='inventory-detail'),
    #path("custom/", custom_workorder_create, name='custom'), #Calls save method for createbase/
    #path("create/", workorder_create_view, name='create'), #Should be obsolete, replaced by createbase/
    path("hx/<str:parent_id>/inventory/", workorder_inventory_update_hx_view, name='hx-inventory-create'),
    path("hx/<str:parent_id>/inventory/<int:id>/", workorder_inventory_update_hx_view, name='hx-workorder-inventory-detail'),
    path("hx/<str:parent_id>/invoice/", workorder_invoice_update_hx_view, name='hx-invoice-add'),
    #path("hx/<str:parent_id>/invoice/<int:id>/", workorder_invoice_update_hx_view, name='hx-workorder-invoice-detail'),
    path("hx/<str:parent_id>/noninventory/", workorder_noninventory_update_hx_view, name='hx-noninventory-create'),
    path("hx/<str:parent_id>/noninventory/<int:id>/", workorder_noninventory_update_hx_view, name='hx-workorder-noninventory-detail'),
    path("hx/<str:parent_id>/service/", workorder_service_update_hx_view, name='hx-service-create'),
    path("hx/<str:parent_id>/service/<int:id>/", workorder_service_update_hx_view, name='hx-workorder-service-detail'),
    path("hx/<str:id>/", workorder_detail_hx_view, name='hx-detail'),
    path("<str:id>/servicedetail", workorder_service_detail, name='service-detail'),
    path("<str:id>/inventorydetail", workorder_inventory_detail, name='inventory-detail'),
    path("<str:id>/delete", workorder_delete_view, name='delete'),
    path("<str:id>/edit", workorder_update_view, name='update'),
    path("<str:id>/", workorder_detail_view, name='detail'),

    
]

workorders/models.py
from time import time
from django.db import models
from django.conf import settings
from django.urls import reverse
from inventory.utils import number_str_to_float
from inventory.validators import validate_unit_of_measure
from customers.models import Customer, Contact
from inventory.models import NonInventory, Inventory, Service, Measurement
#import pint

# Create your models here.
class Workorder(models.Model):
    customer = models.ForeignKey(Customer, blank=True, null=True, on_delete=models.CASCADE)
    contact = models.ForeignKey(Contact, blank=True, null=True, on_delete=models.SET_NULL)
    #company = models.OneToOneField(Customer, on_delete=models.CASCADE, blank=True, null=True)
    workorder = models.CharField('Workorder', max_length=100, blank=False, null=False, unique=True)
    description = models.CharField('Description', max_length=100, blank=True, null=True)
    deadline = models.DateField('Deadline', blank=True, null=True)
    budget = models.CharField('Budget', max_length=100, blank=True, null=True)
    quoted_price = models.CharField('Quoted Price', max_length=100, blank=True, null=True)

    def __str__(self):
        return self.workorder

    def get_absolute_url(self):
        #return "/pantry/recipes/"
        return reverse("workorders:detail", kwargs={"id": self.workorder})

    def get_edit_url(self): #reference these, that way changes are only made one place
        return reverse("workorders:update", kwargs={"id": self.id})

    def get_delete_url(self): #reference these, that way changes are only made one place
        return reverse("workorders:delete", kwargs={"id": self.id})

    def get_contacts_children(self):
        return self.contact_set.all()

    def get_services_children(self):
        return self.workorderservice_set.all()

    def get_inventory_children(self):
        return self.workorderinventoryproduct_set.all()

    def get_noninventory_children(self):
        return self.workordernoninventoryproduct_set.all()

class WorkorderService(models.Model):
    workorder = models.ForeignKey(Workorder, blank=False, null=True, on_delete=models.SET_NULL)
    item = models.ForeignKey(Service, blank=True, null=True, on_delete=models.SET_NULL)
    description = models.CharField('Description', max_length=200, blank=True, null=True)
    billable_time = models.DecimalField('Billable Time', max_digits=10, decimal_places=2, blank=True, null=True)
    default_rate = models.DecimalField('Default Rate', max_digits=10, decimal_places=2, blank=True, null=True)
    custom_rate = models.DecimalField('Custom Rate', max_digits=10, decimal_places=2, blank=True, null=True)

    #def __str__(self):
    #    return self.item.name

    def get_absolute_url(self):
        return self.workorder.get_absolute_url()

    """def get_delete_url(self): #reference these, that way changes are only made one place
        kwargs = {
            "parent_id": self.workorder.id,
            "id": self.id
        }
        return reverse("workorders:delete", kwargs=kwargs)"""
    
    def get_hx_edit_url(self):
        kwargs = {
            "parent_id": self.workorder.id,
            "id": self.id
        }
        return reverse("workorders:hx-workorder-service-detail", kwargs=kwargs)
    
    @property
    def line_total_default(self):
        if self.billable_time is None:
            billable = 0
        else:
            billable = float(self.billable_time)
        if self.custom_rate is None:
            self.custom_rate = 0
            if self.default_rate is None:
                #print(2)
                self.default_rate = 0
                rate = 0
            else:
                #print(3)
                rate = float(self.default_rate)
        if self.custom_rate == 0:
            #print(4)
            rate = float(self.default_rate)
        else:
            #print(5)
            rate = float(self.custom_rate)
        line = billable * rate
        line = '$' + format(line, ',.2f')
        return line

   # @property
    #def Line_total_default(self):
    #	line = self.default_rate * self.billable_time
	#    return line_total_default

class WorkorderInventoryProduct(models.Model):
    workorder = models.ForeignKey(Workorder, blank=False, null=True, on_delete=models.SET_NULL)
    item = models.ForeignKey(Inventory, blank=True, null=True, on_delete=models.SET_NULL)
    description = models.CharField('Description', max_length=100, blank=True, null=True)
    measurement = models.ForeignKey(Measurement, blank=True, null=True, on_delete=models.SET_NULL)
    custom_measurement = models.ForeignKey(Measurement, related_name='+', blank=True, null=True, on_delete=models.SET_NULL)
    #custom_measurement = models.CharField('Custom Measurement', max_length=100, blank=True, null=True)
    qty = models.CharField('Qty', max_length=100, blank=True, null=True)
    price = models.CharField('Price', max_length=100, blank=True, null=True)
    custom_rate = models.DecimalField('Custom Rate', max_digits=10, decimal_places=2, blank=True, null=True)


    #def __str__(self):
    #    return self.item.name

    def get_absolute_url(self):
        return self.workorder.get_absolute_url()
    
    def get_hx_edit_url(self):
        kwargs = {
            "parent_id": self.workorder.id,
            "id": self.id
        }
        return reverse("workorders:hx-workorder-inventory-detail", kwargs=kwargs)

    @property
    def line_total_default(self):
        if self.qty is None:
            amt = 0
        else:
            amt = float(self.qty)
        if self.custom_rate is None:
            self.custom_rate = 0
            if self.price is None:
                #print(2)
                self.price = 0
                rate = 0
            else:
                #print(3)
                rate = float(self.price)
        if self.custom_rate == 0:
            #print(4)
            rate = float(self.price)
        else:
            #print(5)
            rate = float(self.custom_rate)
        line = amt * rate
        line = '$' + format(line, ',.2f')
        return line

    @property
    def measure(self):
        if self.custom_measurement is None:
            measure = self.measurement
        else:
            measure = self.custom_measurement
        return measure



class WorkorderNonInventoryProduct(models.Model):
    workorder = models.ForeignKey(Workorder, blank=False, null=True, on_delete=models.SET_NULL)
    item = models.ForeignKey(NonInventory, blank=True, null=True, on_delete=models.SET_NULL)
    description = models.CharField('Description', max_length=100, blank=True, null=True)
    measurement = models.ForeignKey(Measurement, blank=True, null=True, on_delete=models.SET_NULL)
    custom_measurement = models.ForeignKey(Measurement, related_name='+', blank=True, null=True, on_delete=models.SET_NULL)
    qty = models.CharField('Qty', max_length=100, blank=True, null=True)
    price = models.CharField('Price', max_length=100, blank=True, null=True)
    custom_rate = models.DecimalField('Custom Rate', max_digits=10, decimal_places=2, blank=True, null=True)

    #def __str__(self):
    #    return self.item.name

    def get_absolute_url(self):
        return self.workorder.get_absolute_url()
    
    def get_hx_edit_url(self):
        kwargs = {
            "parent_id": self.workorder.id,
            "id": self.id
        }
        return reverse("workorders:hx-workorder-noninventory-detail", kwargs=kwargs)

    @property
    def line_total_default(self):
        if self.qty is None:
            amt = 0
        else:
            amt = float(self.qty)
        if self.custom_rate is None:
            self.custom_rate = 0
            if self.price is None:
                #print(2)
                self.price = 0
                rate = 0
            else:
                #print(3)
                rate = float(self.price)
        if self.custom_rate == 0:
            #print(4)
            rate = float(self.price)
        else:
            #print(5)
            rate = float(self.custom_rate)
        line = amt * rate
        line = '$' + format(line, ',.2f')
        return line

    @property
    def measure(self):
        if self.custom_measurement is None:
            measure = self.measurement
        else:
            measure = self.custom_measurement
            #measure = "<b>" + str(measure) +"</b>"
        return measure

class WorkorderInvoice(models.Model):
    workorder = models.ForeignKey(Workorder, blank=False, null=True, on_delete=models.SET_NULL)
    #item = models.ForeignKey(NonInventory, blank=True, null=True, on_delete=models.SET_NULL)
    description = models.CharField('Description', max_length=100, blank=True, null=True)
    invoice_image = models.ImageField(null=True, blank=True, upload_to="invoices/")

workorders/forms.py
from django.utils.safestring import mark_safe
from django import forms
from .models import Workorder, WorkorderService, WorkorderInventoryProduct, WorkorderNonInventoryProduct, WorkorderInvoice
from customers.models import Customer, Contact
from dynamic_forms import DynamicField, DynamicFormMixin

class WorkorderForm(DynamicFormMixin, forms.ModelForm):
    required_css_class = 'required-field'
    description = forms.CharField(widget=forms.Textarea())
    class Meta:
        model = Workorder
        fields = ['contact', 'workorder', 'description', 'deadline', 'budget', 'quoted_price']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            #print(field)
            new_data = {
                "placeholder": f'{str(field)}',
                "class": 'form-control',
                #"hx-post": "",
                #"hx-trigger": "keyup changed delay:500ms",
                #"hx-target": "#recipe-container",
                #"hx-swap": "outerHTML"
            }
            self.fields[str(field)].widget.attrs.update(
                new_data
            )
        self.fields['description'].widget.attrs.update({'rows': '2'})
        self.fields['contact'].label = ''

class WorkorderServiceForm(forms.ModelForm):
    class Meta:
        model = WorkorderService
        fields = ['item', 'description', 'billable_time', 'default_rate', 'custom_rate']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            #print(field)
            new_data = {
                "placeholder": f'{str(field)}',
                "class": 'form-control',
            }
            self.fields[str(field)].widget.attrs.update(
                new_data
            )

class WorkorderInventoryForm(forms.ModelForm):
    class Meta:
        model = WorkorderInventoryProduct
        fields = ['item', 'description', 'qty', 'price', 'measurement', 'custom_measurement', 'custom_rate']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            #print(field)
            new_data = {
                "placeholder": f'{str(field)}',
                "class": 'form-control',
            }
            self.fields[str(field)].widget.attrs.update(
                new_data
            )

class WorkorderNonInventoryForm(forms.ModelForm):
    class Meta:
        model = WorkorderNonInventoryProduct
        fields = ['item', 'description', 'qty', 'price', 'measurement', 'custom_measurement', 'custom_rate']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            #print(field)
            new_data = {
                "placeholder": f'{str(field)}',
                "class": 'form-control',
            }
            self.fields[str(field)].widget.attrs.update(
                new_data
            )

class WorkorderInvoiceForm(forms.ModelForm):
    class Meta:
        model = WorkorderInvoice
        fields = ['description', 'invoice_image']

templates/workorders/add-update.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block content %}

<style>
    .contact-form{
        border-bottom: 1px solid black;
    }
    .hidden{
        display: none
    }
</style>

<h1>Add / Update Workorder</h1> 
<p>
<h3>Customer: {{ object.customer }}</h3>
<a href='{{ object.get_absolute_url }}'>Back to Details</a></small><br/>

<div style='margin-top:30px;'>

    <!-- {{ form.customer.label_tag }}
        {% render_field form.customer class="custom-select mb-4" autocomplete="off" hx-get="/workorders/contact/" hx-target="#id_contact" %}
    -->
       <!-- {{ form.contact.label_tag }}
        {% render_field form.contact class="custom-select mb-4" autocomplete="off" %} -->

    {% include 'workorders/partials/forms.html' %}
    <p>
    <p>
    <h3>Invoices:</h3>
    <div id='invoice-add'>

    </div>
    <button hx-get="{{ new_invoice_url }}" hx-trigger='click' hx-target='#invoice-add' hx-swap='beforeend'>Add Invoice</button>
    <p>
    <p>
    {% if titles %}
        <!-- Add Services-->
        <h3>Services:</h3>
        <table class="table table-bordered">
            <tr>
                <th>Item</th>
                <th>Qty</th>
                <th>Rate</th>
                <th>Description</th>
                <th></th>
        {% for item in object.get_services_children %}
            {% include 'workorders/partials/service-inline.html' with object=item %}
        {% endfor %}
        </table>
        {% if new_service_url %}
        <div id='service-create'>

        </div>


        <button hx-get="{{ new_service_url }}" hx-trigger='click' hx-target='#service-create' hx-swap='beforeend'>Add Service</button>
        {% endif %}

        <!-- Add Inventory Items -->
        <p>
        <p>
        <h3>Inventory Items:</h3>
        <table class="table table-bordered">
            <tr>
                <th>Item</th>
                <th>Qty</th>
                <th>Measurement</th>
                <th>Price ea</th>
                <th>Description</th>
                <th></th>
            </tr>
        {% for item in object.get_inventory_children %}
            {% include 'workorders/partials/inventory-inline.html' with object=item %}
        {% endfor %}
        </table>
        {% if new_inventory_url %}
        <div id='inventory-create'>

        </div>

            
        <button hx-get="{{ new_inventory_url }}" hx-trigger='click' hx-target='#inventory-create' hx-swap='beforeend'>Add Inventory Item</button>
        {% endif %}

        <!-- Add Non Inventory Items-->
        <p>
        <p>
        <h3>Non Inventory Items:</h3>
        <table class="table table-bordered">
            <tr>
                <th>Item</th>
                <th>Qty</th>
                <th>Measurement</th>
                <th>Price ea</th>
                <th>Description</th>
                <th></th>
            </tr>
        {% for item in object.get_noninventory_children %}
            {% include 'workorders/partials/noninventory-inline.html' with object=item %}
        {% endfor %}
        </table>
        {% if new_noninventory_url %}
        <div id='noninventory-create'>

        </div>


        <button hx-get="{{ new_noninventory_url }}" hx-trigger='click' hx-target='#noninventory-create' hx-swap='beforeend'>Add NonInventory Item</button>
        {% endif %}
    {% endif %}

</div>


{% endblock content %}

templates/workorders/create-workorder.html
{% extends "base.html" %}


{% block content %}




<div>
    <form action='/workorders/createbase/' method="POST">
        {% csrf_token %}
        
        {% if error %}
        {{ error }}
        <br/>
        {% endif %}

        <select class="custom-select mb-4" name='customer' hx-get="{% url 'workorders:contacts' %}" hx-trigger="change" hx-target="#contacts">
            <option value="0" selected>Customer</option>
            {% for customer in customers %}
                <option value="{{customer.pk}}">{{ customer.name }}</option>
            {% endfor %}
        </select> <a href="{% url 'customers:create' %}">Add Customer</a>

        <div id="contacts">
                {% include 'workorders/partials/contact-dropdown.html' %}
        </div>
        
        {% if workordererror %}
        {{ workordererror }}
        {% endif %}
        <div><input type='text' name='workorder' placeholder='Workorder' /></div>
        <!-- <div><textarea name='description' placeholder='Description'></textarea></div>
        <div><input type='text' name='deadline' placeholder='Deadline'></div>
        <div><input type='text' name='budget' placeholder='Budget'/></div>
        <div><input type='text' name='quoted_price' placeholder='Quoted Price'/></div> -->
        <input type='submit' value='Create Workorder'></div>
    </form>
</div>

{% endblock content %}

templates/workorders/delete.html
{% extends "base.html" %}

{% block content %}

{% if object %}
<form method='POST' action=''>
    {% csrf_token %}
    <p> Are you sure you want to delete {{ object.workorder }}</p>

    <button type='submit'> Yes, delete</button>
</form>

{% endif %}

{% endblock content %}

templates/workorders/detail.html
{% extends "base.html" %}

{% block content %}

<div hx-get='{{ hx_url }}' hx-trigger='revealed'>
    <div class='htmx-indicator'>Loading...</div>
</div>

{% endblock content %}

templates/workorders/list.html
{% extends "base.html" %}

{% block content %}
<h1>Workorders</h1> 



<a href="{% url 'workorders:createbase' %}">Add Workorder</a>

<p><ul>
    {% for x in  object_list %}
    <li><a href='{{ x.get_absolute_url }}'>{{ x.workorder }} - {{ x.description }}</a></li>
    {% endfor %}
    </ul></p>






{% endblock content %}