customers/urls.py
from django.urls import path

from .views import (
    customer_list_view,
    customer_create_view,
    customer_detail_view,
    customer_update_view,
    customer_detail_hx_view,
    customer_contact_update_hx_view,
    autosuggest,
)

app_name='customers'
urlpatterns = [
    path("", customer_list_view, name='list'),
    path("create/", customer_create_view, name='create'),
    path("name-autosuggest/", autosuggest, name='name-autosuggest'),
    path("hx/<int:parent_id>/contacts/<int:id>/", customer_contact_update_hx_view, name='hx-contact-detail'),
    path("hx/<int:parent_id>/contacts/", customer_contact_update_hx_view, name='hx-contact-create'),
    path("hx/<int:id>/", customer_detail_hx_view, name='hx-detail'),
    path("<int:id>/edit", customer_update_view, name='update'),
    path("<int:id>/", customer_detail_view, name='detail'),
]

inventory/urls.py
from django.urls import path

from .views import (
    category_list_view,
    mpn_create_view,
    mpn_list_view,
    mpn_detail_view,
    mpn_detail_hx_view,
    mpn_update_view,
    manufacturer_create_view,
    service_create_view,
    service_list_view,
    inventory_create_view,
    inventory_list_view,
    add_category_view,
    get_parent_view,
    add_measurement_view,
    mpn_autosuggest,
    manufacturer_autosuggest,
    measurement_autosuggest,
    add_mpn

)

app_name='inventory'
urlpatterns = [
    path("create-mpn/", mpn_create_view, name='create-mpn'),
    path("add-manufacturer/", manufacturer_create_view, name='add-manufacturer'),
    path("add-service/", service_create_view, name='add-service'),
    path("service-list/", service_list_view, name='service-list'),
    path("add-inventory/", inventory_create_view, name='add-inventory'),
    path("add-inventory/add-mpn", add_mpn, name='add-mpn'),
    path("add-measurement/", add_measurement_view, name='add-measurement'),
    path("inventory-list/", inventory_list_view, name='inventory-list'),
    path("mpn-list/", mpn_list_view, name='mpn-list'),
    path("mpn/<int:id>/", mpn_detail_hx_view, name='hx-mpn-detail'),
    path("<int:id>/", mpn_detail_view, name='mpn-detail'),
    path("<int:id>/edit", mpn_update_view, name='mpn-update'),
    path("add-category/", add_category_view, name='add-category'),
    path("add-category/getparent", get_parent_view, name='get-parent'),
    path("mpn-autosuggest/", mpn_autosuggest, name='mpn-autosuggest'),
    path("manufacturer-autosuggest/", manufacturer_autosuggest, name='manufacturer-autosuggest'),
    path("measurement-autosuggest/", measurement_autosuggest, name='measurement-autosuggest'),
    #path("", inventory_list_view, name='list'),
    #path("create/", customer_create_view, name='create'),
    #path("hx/<int:parent_id>/contacts/<int:id>/", customer_contact_update_hx_view, name='hx-contact-detail'),
    #path("hx/<int:parent_id>/contacts/", customer_contact_update_hx_view, name='hx-contact-create'),
    #path("hx/<int:id>/", customer_detail_hx_view, name='hx-detail'),
    #path("<int:id>/edit", customer_update_view, name='update'),
    #path("<int:id>/", inventory_detail_view, name='detail')
    #path("/ia/<int:parent>/", category_list_view, name='category-list') #Attmpting to get this to work
    path("admin/category/", category_list_view, name='category-list'), #Testing to get above to work
    path("admin/category/<int:parent>/", category_list_view, name='category-list'),
]

purchase_orders/urls.py
from django.urls import path

from .views import (
    po_create_view,
    po_detail_view,
    po_detail_hx_view,
    po_list_view,
)

app_name='purchase_orders'
urlpatterns = [
    path("create-po/", po_create_view, name='create-po'),
    path("po/", po_list_view, name='po-list'),
    path("po/<int:id>/", po_detail_hx_view, name='hx-po-detail'),
    path("<int:id>/", po_detail_view, name='po-detail'),
]

studio_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import home_view

urlpatterns = [
    path('', home_view, name='home'),
    path('admin/', admin.site.urls),
    #path('', include('userprofile.urls')),
    path('userprofile/', include('django.contrib.auth.urls')),
    path('userprofile/', include('userprofile.urls')),
    path('customers/', include('customers.urls')),
    path('inventory/', include('inventory.urls')),
    path('purchase_orders/', include('purchase_orders.urls')),
    path('vendors/', include('vendors.urls')),
    path('workorders/', include('workorders.urls')),
    #path('scratch/', include('scratch.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vendors/urls.py
from django.urls import path

from .views import (
    vendor_list_view,
    vendor_create_view,
    vendor_detail_view,
    vendor_update_view,
    vendor_detail_hx_view,
    vendor_contact_update_hx_view,
)

app_name='vendors'
urlpatterns = [
    path("", vendor_list_view, name='list'),
    path("create/", vendor_create_view, name='create'),
    path("hx/<int:parent_id>/contacts/<int:id>/", vendor_contact_update_hx_view, name='hx-contact-detail'),
    path("hx/<int:parent_id>/contacts/", vendor_contact_update_hx_view, name='hx-contact-create'),
    path("hx/<int:id>/", vendor_detail_hx_view, name='hx-detail'),
    path("<int:id>/edit", vendor_update_view, name='update'),
    path("<int:id>/", vendor_detail_view, name='detail')
]

workorders/urls.py
from django.urls import path

from .views import (
    workorder_list_view,
    #workorder_create_view,
    workorder_detail_view,
    workorder_delete_view,
    workorder_detail_hx_view,
    workorder_update_view,
    workorder_inventory_update_hx_view,
    workorder_noninventory_update_hx_view,
    workorder_service_update_hx_view,
    workorder_invoice_update_hx_view,
    create_base,
    contacts,
    update_contact,
    #custom_workorder_create,
    service_detail,
    inventory_detail,
    workorder_service_detail,
    workorder_inventory_detail,
    
)

app_name='workorders'
urlpatterns = [
    path("", workorder_list_view, name='list'), #List All workorders
    path("createbase/", create_base, name='createbase'), #Create base details of new workorder
    path('contacts/', contacts, name='contacts'), #Fills the contact dropdown on createbase/
    path('updatecontact/', update_contact, name='update-contact'), ####
    path('servicedetail/', service_detail, name='service-detail'),
    path('inventorydetail/', inventory_detail, name='inventory-detail'),
    #path("custom/", custom_workorder_create, name='custom'), #Calls save method for createbase/
    #path("create/", workorder_create_view, name='create'), #Should be obsolete, replaced by createbase/
    path("hx/<str:parent_id>/inventory/", workorder_inventory_update_hx_view, name='hx-inventory-create'),
    path("hx/<str:parent_id>/inventory/<int:id>/", workorder_inventory_update_hx_view, name='hx-workorder-inventory-detail'),
    path("hx/<str:parent_id>/invoice/", workorder_invoice_update_hx_view, name='hx-invoice-add'),
    #path("hx/<str:parent_id>/invoice/<int:id>/", workorder_invoice_update_hx_view, name='hx-workorder-invoice-detail'),
    path("hx/<str:parent_id>/noninventory/", workorder_noninventory_update_hx_view, name='hx-noninventory-create'),
    path("hx/<str:parent_id>/noninventory/<int:id>/", workorder_noninventory_update_hx_view, name='hx-workorder-noninventory-detail'),
    path("hx/<str:parent_id>/service/", workorder_service_update_hx_view, name='hx-service-create'),
    path("hx/<str:parent_id>/service/<int:id>/", workorder_service_update_hx_view, name='hx-workorder-service-detail'),
    path("hx/<str:id>/", workorder_detail_hx_view, name='hx-detail'),
    path("<str:id>/servicedetail", workorder_service_detail, name='service-detail'),
    path("<str:id>/inventorydetail", workorder_inventory_detail, name='inventory-detail'),
    path("<str:id>/delete", workorder_delete_view, name='delete'),
    path("<str:id>/edit", workorder_update_view, name='update'),
    path("<str:id>/", workorder_detail_view, name='detail'),

    
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
{% block scripts %}
{% endblock %}
  <head>
    <script src="https://unpkg.com/htmx.org@1.7.0"></script>
    <link rel='stylesheet' href='{% static "workorders/workorders-htmx.css" %}' />

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


    <!-- Date TIme Picker CSS -->
    <link rel="stylesheet" href="{% static 'date-time-phone/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'date-time-phone/jquery-ui-timepicker-addon.css' %}">
    <!-- Date Time Picker CSS -->

    <title>Studio Management</title>
    <style>
      body {background: #32396e;}
    </style>

  </head>
  <body>
    {% include 'navbar.html' %}
    <br></br>
    <div class="shadow p-4 mb-5 bg-body rounded">
    <div class="container">
      {% if messages %}
        {% for message in messages %}

          <div class="alert alert-warning alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>

        {% endfor %}
      {% endif %}

      {% block content %}

      {% endblock %}

    </div>


    <!-- Autocomplete fields 
      https://www.youtube.com/watch?v=aHzN92LqWf0 -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
    <!-- <link rel="stylesheet" href="/resources/demos/style.css"> -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
			  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
			  crossorigin="anonymous">
    </script>
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
    <script>

        $( "#id_internal_part_number" ).autocomplete({
          source: "{% url 'inventory:mpn-autosuggest' %}"
        });

        $( "#id_name" ).autocomplete({
          source: "{% url 'customers:name-autosuggest' %}"
        });

        $( "#manufacturer" ).autocomplete({
          source: "{% url 'inventory:manufacturer-autosuggest' %}"
        });

        $( "#measurement" ).autocomplete({
          source: "{% url 'inventory:measurement-autosuggest' %}"
        });

      </script>
    <!-- End of Autcomplete -->

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    
    <!-- Core plugin JavaScript -->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    
    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>
    <script>
    setTimeout(function(){
      if ($('#msg').length > 0) {
        $('#msg').remove();
      }
    }, 2000)
    </script>

    <!-- Date Time Picker JS -->
    <script src="{% static 'date-time-phone/jquery-ui.js' %}" ></script>
    <script src="{% static 'date-time-phone/jquery-ui-timepicker-addon.js' %}" ></script>
  
    <script>
      $( function() {
          // $( "#id_date" ).datetimepicker({ dateFormat: 'yy-mm-dd', maxDate: 0, controlType: 'select'}).attr("autocomplete", "off") ;
          // $( "#id_date" ).timepicker({ dateFormat: 'yy-mm-dd', maxDate: 0, controlType: 'select'}).attr("autocomplete", "off") ;
          // $( "#id_date" ).datepicker({ dateFormat: 'yy-mm-dd'}).attr("autocomplete", "off") ;
      });
      $( function() {
          //$( "#id_date" ).datetimepicker({ dateFormat: 'yy-mm-dd', maxDate: 0, controlType: 'select'}).attr("autocomplete", "off") ;
          // $( "#id_date" ).timepicker({ dateFormat: 'yy-mm-dd', maxDate: 0, controlType: 'select'}).attr("autocomplete", "off") ;
          $( "#id_date" ).datepicker({ dateFormat: 'yy-mm-dd'}).attr("autocomplete", "off") ;
      });
      $( function() {
          //$( "#id_deadline" ).datetimepicker({ dateFormat: 'yy-mm-dd', controlType: 'select'}).attr("autocomplete", "off") ;
          // $( "#id_date" ).timepicker({ dateFormat: 'yy-mm-dd', maxDate: 0, controlType: 'select'}).attr("autocomplete", "off") ;
          $( "#id_deadline" ).datepicker({ dateFormat: 'yy-mm-dd'}).attr("autocomplete", "off") ;
      });
    </script>
  
    <!-- Date time picker -->

    <!-- Phone Mask JS -->
    <script src="{% static 'date-time-phone/jquery-input-mask-phone-number.min.js' %}"></script>

    <script>
      //(xxx) xxx-xxxx format code
      $(document).ready(function () {
          $('#id_phone1').usPhoneFormat({
              format: '(xxx) xxx-xxxx',
          });
          $('#id_phone2').usPhoneFormat({
              format: '(xxx) xxx-xxxx',
          });
      });
    </script>
    <!-- Phone Mask JS -->
  </body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
<h1>Hello World!</h1> 




{% endblock content %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">{LK}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
            {% if user.is_superuser %}
            <li class="nav-item">
              <a class="nav-link" href="/admin">Admin</a>
            </li>
            {% endif %}
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'register' %}">Register</a>
            </li>
  
  
  
          {% endif %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Workorders
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><a class="dropdown-item" href="{% url 'workorders:list' %}">Workorder List</a></li>
              <li><a class="dropdown-item" href="{% url 'workorders:createbase' %}">Add Workorder</a></li>
                            
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="{% url 'customers:list' %}" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Customers
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><a class="dropdown-item" href="{% url 'customers:list' %}">Customer List</a></li>
              <li><a class="dropdown-item" href="{% url 'customers:create' %}">Add Customer</a></li>
              <!-- <li><a class="dropdown-item" href="">Add Customer Contact</a></li> -->
            </ul> 
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Vendors
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><a class="dropdown-item" href="{% url 'vendors:list' %}">Vendor List</a></li>
              <li><a class="dropdown-item" href="{% url 'vendors:create' %}">Add Vendor</a></li>

              <!-- <li><a class="dropdown-item" href="">Add Customer Contact</a></li> -->
            </ul> 
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Inventory
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><a class="dropdown-item" href="{% url 'purchase_orders:create-po' %}">Add Purchase Order</a></li>
              <li><a class="dropdown-item" href="{% url 'purchase_orders:po-list' %}">Purchase Order List</a></li>
	            <li><a class="dropdown-item" href="{% url 'inventory:add-service' %}">Add Service</a></li>
              <li><a class="dropdown-item" href="{% url 'inventory:service-list' %}">Service List</a></li>
	            <li><a class="dropdown-item" href="{% url 'inventory:add-inventory' %}">Add Inventory Item</a></li>
              <li><a class="dropdown-item" href="{% url 'inventory:inventory-list' %}">Inventory List</a></li>
	            <li><a class="dropdown-item" href="#">Add NonInventory Item#</a></li>
	            <li><a class="dropdown-item" href="#">NonInventory List#</a></li>
            </ul> 
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Admin
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><a class="dropdown-item" href="{% url 'inventory:category-list' %}">Inventory Category List</a></li>
              <li><a class="dropdown-item" href="{% url 'inventory:add-category' %}">Add Inventory Category</a></li>
              <li><a class="dropdown-item" href="#">Update Inventory Category #</a></li>
              <li><a class="dropdown-item" href="{% url 'inventory:add-measurement' %}">Add Measurement</a></li>
              <li><a class="dropdown-item" href="{% url 'inventory:add-manufacturer' %}">Add Manufacturer</a></li>
              <li><a class="dropdown-item" href="{% url 'inventory:mpn-list' %}">Master Part Number List</a></li>
              <li><a class="dropdown-item" href="{% url 'inventory:create-mpn' %}">Add Master Part Number</a></li>
            </ul> 
          </li>
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Future Items
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><a class="dropdown-item" href="">Timecard #</a></li>
              <li><a class="dropdown-item" href="#">Dynamic Customer</a></li>
              <li><a class="dropdown-item" href="#">Add Workorder</a></li>
              <li><a class="dropdown-item" href="#">Custom Form</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  